services:
  - type: web
    name: telegram-bot
    env: python
    region: oregon  # You can change the region if needed
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "7975644638:AAFrZ1FxLMZlaGE98is3wzZqBWnp_9ErNnY"  # Replace with your bot token
      - key: DISK_PATH
        value: "/data"
    disk:
      - name: persistent-data
        mountPath: /data
